apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - patch: |
      - op: replace
        path: /spec/listeners/0/hostname
        value: slack-inviter.staging.env.datum.net
      - op: replace
        path: /spec/listeners/1/hostname
        value: slack-inviter.staging.env.datum.net
    target:
      kind: Gateway
      name: slack-inviter-gateway